const NUMERO_WHATSAPP = "5511940168045";

const produtos = [
  {
    id: 1,
    nome: "Vestido Midi Floral",
    categoria: "feminino",
    preco: 129.9,
    precoAntigo: 169.9,
    cor: "#e75480",
    descricao: "Vestido midi com estampa floral, tecido leve e fluido, perfeito para o dia a dia e ocasiões especiais. Disponível nos tamanhos P ao GG.",
    emOferta: true,
  },
  {
    id: 2,
    nome: "Blusa Cropped Canelada",
    categoria: "feminino",
    preco: 49.9,
    precoAntigo: 69.9,
    cor: "#9b6b8e",
    descricao: "Cropped de malha canelada com excelente elasticidade e caimento. Combina com saias, calças e shorts.",
    emOferta: false,
  },
  {
    id: 3,
    nome: "Calça Jeans Skinny",
    categoria: "feminino",
    preco: 99.9,
    precoAntigo: 139.9,
    cor: "#4a6fa5",
    descricao: "Calça jeans skinny com elastano, conforto e modelagem que valoriza o corpo. Lavagem média.",
    emOferta: true,
  },
  {
    id: 4,
    nome: "Saia Plissada",
    categoria: "feminino",
    preco: 79.9,
    precoAntigo: 99.9,
    cor: "#d96c75",
    descricao: "Saia plissada moderna, com cintura alta e movimento lindo. Ideal para looks casuais e sociais.",
    emOferta: false,
  },
  // ex de como colocar iamgem no site, fazer isso apra todos : obs: exemplo a baixo
  {
  id: 5,
  nome: "Camisa Social Feminina",
  imagem: "fotos/feminino-camisa-feminina-social-manga-longa-linho.jpg",
  categoria: "feminino",
  preco: 199.9,
  precoAntigo: 259.9,
  cor: "#8e3b6f",
  descricao: "Camisa feminina social de manga longa em linho, elegante e confortável para o trabalho e eventos.",
  emOferta: false,
},
  {
    id: 6,
    nome: "Camisa Social Masculina",
    imagem: "fotos/camisa_social_marinho_masculina_slim_manga_longa_anticorpus_.webp",
    categoria: "masculino",
    preco: 89.9,
    precoAntigo: 119.9,
    cor: "#5b7a9d",
    descricao: "Camisa social de algodão, com caimento perfeito e toque macio. Disponível do M ao GG.",
    emOferta: false,
  },
  {
    id: 7,
    nome: "Camiseta Básica Premium",
    categoria: "masculino",
    preco: 39.9,
    precoAntigo: 54.9,
    cor: "#3d5a6c",
    descricao: "Camiseta básica premium em algodão penteado, com gola reforçada. A peça coringa do guarda-roupa.",
    emOferta: true,
  },
  {
    id: 8,
    nome: "Calça Jeans Masculina",
    categoria: "masculino",
    preco: 109.9,
    precoAntigo: 149.9,
    cor: "#47698a",
    descricao: "Calça jeans masculina reta, lavagem azul escura. Durável e confortável para todas as ocasiões.",
    emOferta: false,
  },
  {
    id: 9,
    nome: "Bermuda Masculina",
    categoria: "masculino",
    preco: 69.9,
    precoAntigo: 89.9,
    cor: "#6b7d52",
    descricao: "Bermuda masculina com tecido de secagem rápida, ideal para o verão e atividades ao ar livre.",
    emOferta: false,
  },
  {
    id: 10,
    nome: "Vestido Infantil Floral",
    categoria: "infantil",
    preco: 59.9,
    precoAntigo: 79.9,
    cor: "#f2a0b5",
    descricao: "Vestido infantil com estampa floral, tecido confortável e sem etiqueta. Tamanhos 2 ao 12.",
    emOferta: false,
  },
  {
    id: 11,
    nome: "Camiseta Infantil Colorida",
    categoria: "infantil",
    preco: 34.9,
    precoAntigo: 44.9,
    cor: "#f29a4a",
    descricao: "Camiseta infantil de algodão, leve e fresquinha. Cores vibrantes que as crianças adoram.",
    emOferta: true,
  },
  {
    id: 12,
    nome: "Tênis Infantil",
    categoria: "infantil",
    preco: 79.9,
    precoAntigo: 109.9,
    cor: "#58a6a0",
    descricao: "Tênis infantil com velcro, leve e flexível, ideal para brincar com segurança e conforto.",
    emOferta: false,
  },
  {
    id: 13,
    nome: "Tênis Feminino Casual",
    categoria: "calcados",
    preco: 149.9,
    precoAntigo: 199.9,
    cor: "#e7a6b8",
    descricao: "Tênis feminino casual em couro sintético, com solado confortável. Combina com tudo.",
    emOferta: true,
  },
  {
    id: 14,
    nome: "Sandália Salto Grosso",
    categoria: "calcados",
    preco: 119.9,
    precoAntigo: 159.9,
    cor: "#b05c7a",
    descricao: "Sandália de salto grosso com tira ajustável, firme e elegante. Perfeita para o dia e a noite.",
    emOferta: false,
  },
  {
    id: 15,
    nome: "Sapatilha Feminina",
    categoria: "calcados",
    preco: 89.9,
    precoAntigo: 119.9,
    cor: "#7d5a8c",
    descricao: "Sapatilha feminina com palmilha de gel, super macia para o dia inteiro de conforto.",
    emOferta: false,
  },
  {
    id: 16,
    nome: "Rasteirinha com Tira",
    categoria: "calcados",
    preco: 49.9,
    precoAntigo: 69.9,
    cor: "#c9873d",
    descricao: "Rasteirinha com tira em V, leve e confortável. A queridinha do verão.",
    emOferta: true,
  },
  {
    id: 17,
    nome: "Bota Cano Curto",
    categoria: "calcados",
    preco: 179.9,
    precoAntigo: 239.9,
    cor: "#5c4033",
    descricao: "Bota de cano curto com zíper lateral, versátil para o inverno. Estilo e proteção.",
    emOferta: false,
  },
  {
    id: 18,
    nome: "Bolsa Transversal",
    categoria: "bolsas",
    preco: 129.9,
    precoAntigo: 169.9,
    cor: "#a0507a",
    descricao: "Bolsa transversal com compartimento para celular e carteira. Prática e cheia de estilo.",
    emOferta: true,
  },
  {
    id: 19,
    nome: "Carteira Feminina",
    categoria: "bolsas",
    preco: 49.9,
    precoAntigo: 69.9,
    cor: "#8a6fb0",
    descricao: "Carteira feminina com muitos porta-cartões e moedeiro. Compacta e organizada.",
    emOferta: false,
  },
  {
    id: 20,
    nome: "Cinto de Couro",
    categoria: "bolsas",
    preco: 39.9,
    precoAntigo: 54.9,
    cor: "#6b4a3a",
    descricao: "Cinto de couro com fivela clássica. Dá acabamento perfeito a qualquer look.",
    emOferta: false,
  },
  {
    id: 21,
    nome: "Óculos de Sol",
    categoria: "bolsas",
    preco: 59.9,
    precoAntigo: 89.9,
    cor: "#3b3b4a",
    descricao: "Óculos de sol com proteção UV400 e armação leve. Estilo para todos os dias.",
    emOferta: true,
  },
  {
    id: 22,
    nome: "Necessaire Organizadora",
    categoria: "variedades",
    preco: 29.9,
    precoAntigo: 39.9,
    cor: "#4f9d8f",
    descricao: "Necessaire com zíper e forro resistente. Ideal para viagens e organização do dia a dia.",
    emOferta: false,
  },
  {
    id: 23,
    nome: "Kit Toalhas de Banho",
    categoria: "variedades",
    preco: 89.9,
    precoAntigo: 129.9,
    cor: "#7f9cba",
    descricao: "Kit com 2 toalhas de banho e 1 rosto em algodão, macias e absorventes.",
    emOferta: true,
  },
  {
    id: 24,
    nome: "Vela Aromática",
    categoria: "variedades",
    preco: 24.9,
    precoAntigo: 34.9,
    cor: "#d9a25a",
    descricao: "Vela aromática de cera vegetal com aroma suave, para deixar sua casa mais aconchegante.",
    emOferta: false,
  },
];
